server:
  port: 8099
#  ssl:
#    enabled: true
#    key-store: file:./22itwxz.cn.jks
#    key-store-password: r9szt2m4n96q
#    key-store-type: JKS
spring:
  application:
    name: repair-station
  data:
    mongodb:
      uri: mongodb://localhost:27017/repair_station
    redis:
      host: localhost
      port: 6379
#      password: 123456
      database: 0
  cache:
    redis:
      cache-null-values: true
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/repair_station
    username: root
    password: 123456
    druid:
      time-between-eviction-runs-millis: 60000  # 检测需要关闭的空闲连接的间隔时间，单位是毫秒
      min-evictable-idle-time-millis: 300000  # 连接保持空闲而不被驱逐的最小时间，单位是毫秒
      remove-abandoned: true  # 是否移除泄露的连接
      remove-abandoned-timeout: 1800  # 超过时间限制，回收没有被关闭的连接
  servlet:
    multipart:
      enabled: true
      max-file-size: 360MB
      max-request-size: 360MB
      file-size-threshold: 10MB
  mail:
    host: smtp.qq.com
    port: 587
    username: 1852520162@qq.com
    password: hlwvudhuvxcyddha
    properties:
      mail:
        smtp:
          auth: true                 # 启用 SMTP 身份验证
          starttls:
            enable: true             # 启用 STARTTLS，加密连接
            required: true           # 强制使用加密连接
      default-encoding: UTF-8          # 设置邮件的默认编码为 UTF-8
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    default-enum-type-handler: com.baomidou.mybatisplus.core.handlers.MybatisEnumTypeHandler
  global-config:
    db-config:
      id-type: ASSIGN_ID

project-config:
  web-url: http://localhost:5173
  email: 1181428703@qq.com
  base-path: D:/
  csv-path: "${project-config.base-path}/csv"
  database-backup-path: "${project-config.base-path}/DB-backup"
  photo-path: "${project-config.base-path}/photo"
